{{- if .Values.deployments }}
{{- $root := . }}
{{- range $name, $deployment := .Values.deployments }}
{{- if kindIs "map" $deployment }}
{{- if not (default false $deployment.disabled) }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
{{- if or (eq (toString $.Values.replicaCountOverwrite) "0") ($.Values.replicaCountOverwrite) }}
  replicas: {{ $.Values.replicaCountOverwrite }}
{{- else if $deployment.replicaCount }}
  replicas: {{ tpl (toString $deployment.replicaCount) $}}
{{- end }}
  selector:
    matchLabels:
      app: {{ $name }}
{{- if $deployment.strategy }}
  strategy:
{{ toYaml $deployment.strategy | indent 4 }}
{{- end }}
  template:
    metadata:
{{- if $deployment.annotations }}
      annotations:
{{ toYaml $deployment.annotations | indent 8 }}
{{- end }}
      labels:
        app: {{ $name }}
    spec:
{{- if $deployment.serviceAccountName }}
      serviceAccountName: {{ $deployment.serviceAccountName }}
{{- end }}
{{- if $deployment.restartPolicy }}
      restartPolicy: {{ $deployment.restartPolicy }}
{{- end }}
{{- if $deployment.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $deployment.terminationGracePeriodSeconds }}
{{- end }}
{{- if $deployment.nodeSelectors }}
      nodeSelector:
{{- range $key, $val := $deployment.nodeSelectors }}
        {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
{{- if $deployment.volumes }}
      volumes:
{{ tpl (toYaml $deployment.volumes) $ | indent 6 }}
{{- end }}
{{- if $deployment.imagePullSecrets }}
      imagePullSecrets:
{{ tpl (toYaml $deployment.imagePullSecrets) $ | indent 6 }}
{{- end }}
      containers:
{{- range $name, $container := $deployment.containers }}
      - name: "{{ $container.name }}"
        image: "{{- tpl ($container.image.repository) $ }}:{{- tpl ($container.image.tag) $ }}"
        imagePullPolicy: {{ $container.image.pullPolicy }}
{{- if $container.command }}
        command:
{{ toYaml $container.command | indent 8 }}
{{- end }}
{{- if $container.args }}
        args:
{{ toYaml $container.args | indent 8 }}
{{- end }}
{{- if $container.containerPorts }}
        ports:
{{ toYaml $container.containerPorts | indent 8 }}
{{- end }}
{{- if and $container.volumeMounts (eq (tpl ($container.volumeMountDisabled | default "false") $) "false") }}
        volumeMounts:
{{ tpl (toYaml $container.volumeMounts) $ | indent 8 }}
{{- end }}
{{- if $container.securityContext }}
        securityContext:
{{ toYaml $container.securityContext | indent 10 }}
{{- end }}
{{- if $container.extraVars }}
        env:
{{ tpl (toYaml $container.extraVars) $ | indent 8 }}
{{- end }}
{{- if $container.envFrom }}
        envFrom:
{{ tpl (toYaml $container.envFrom) $ | indent 8 }}
{{- end }}
{{- if $container.secretKeyRef }}
{{ toYaml $container.secretKeyRef | indent 8 }}
{{- end }}
{{- if $container.livenessProbe }}
        livenessProbe:
{{ toYaml $container.livenessProbe | indent 10 }}
{{- end }}
{{- if $container.lifecycle }}
        lifecycle:
{{ toYaml $container.lifecycle | indent 10 }}
{{- end }}
{{- if $container.startupProbe }}
        startupProbe:
{{ toYaml $container.startupProbe | indent 10 }}
{{- end }}
{{- if $container.readinessProbe }}
        readinessProbe:
{{ toYaml $container.readinessProbe | indent 10 }}
{{- end }}
{{- if $container.resources }}
        resources:
{{ tpl (toYaml $container.resources) $ | indent 10 }}
{{- end }}
{{- end }}

{{- if $deployment.initContainers }}
      initContainers:
{{- range $index, $initContainer := $deployment.initContainers }}
  {{- if ne (tpl (toString $initContainer.disabled) $) "true" }}
      - name: {{ $initContainer.name }}
        image: {{ $initContainer.image }}
        {{- if $initContainer.imagePullPolicy }}
        imagePullPolicy: {{ $initContainer.imagePullPolicy }}
        {{- end }}
        {{- if $initContainer.command }}
        command:
{{ toYaml $initContainer.command | indent 10 }}
        {{- end }}
        {{- if $initContainer.args }}
        args:
{{ toYaml $initContainer.args | indent 10 }}
        {{- end }}
        {{- if $initContainer.volumeMounts }}
        volumeMounts:
{{ toYaml $initContainer.volumeMounts | indent 10 }}
        {{- end }}
        {{- if $initContainer.ports }}
        ports:
{{ toYaml $initContainer.ports | indent 10 }}
        {{- end }}
        {{- if $initContainer.env }}
        env:
{{ toYaml $initContainer.env | indent 10 }}
        {{- end }}
        {{- if $initContainer.envFrom }}
        envFrom:
{{ toYaml $initContainer.envFrom | indent 10 }}
        {{- end }}
        {{- if $initContainer.resources }}
        resources:
{{ toYaml $initContainer.resources | indent 10 }}
        {{- end }}
        {{- if $initContainer.securityContext }}
        securityContext:
{{ toYaml $initContainer.securityContext | indent 10 }}
        {{- end }}
        {{- if $initContainer.lifecycle }}
        lifecycle:
{{ toYaml $initContainer.lifecycle | indent 10 }}
        {{- end }}
        {{- if $initContainer.livenessProbe }}
        livenessProbe:
{{ toYaml $initContainer.livenessProbe | indent 10 }}
        {{- end }}
        {{- if $initContainer.readinessProbe }}
        readinessProbe:
{{ toYaml $initContainer.readinessProbe | indent 10 }}
        {{- end }}
        {{- if $initContainer.terminationMessagePath }}
        terminationMessagePath: {{ $initContainer.terminationMessagePath }}
        {{- end }}
        {{- if $initContainer.terminationMessagePolicy }}
        terminationMessagePolicy: {{ $initContainer.terminationMessagePolicy }}
        {{- end }}
        {{- if $initContainer.workingDir }}
        workingDir: {{ $initContainer.workingDir }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}



{{- if $deployment.affinity }}
      affinity:
{{ toYaml $deployment.affinity | indent 8 }}
{{- end }}
{{- if $deployment.tolerations }}
      tolerations:
{{ toYaml $deployment.tolerations | indent 8 }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}