{{- if .Values.ingresses }}
{{- $root := . }}
{{- range $name, $ingress := .Values.ingresses }}
{{- if not $ingress.disabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
{{- if $ingress.annotations }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
{{- end }}
  labels:
{{- if $ingress.app }}
    app: "{{ $ingress.app }}"
{{- else }}
    app: {{ $name }}
{{- end }}
{{- if $ingress.labels }}
{{ toYaml $ingress.labels | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ $ingress.className }}
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ tpl . $ | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
{{ tpl (toYaml $ingress.rules) $ | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
