{{- if .Values.rolebindings }}
{{- $root := . }}
{{- range $name, $rolebinding := .Values.rolebindings }}
{{- if not $rolebinding.disabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
roleRef:
 kind: Role
 name: {{ $rolebinding.roleName }}
 apiGroup: {{ $rolebinding.apiGroup }}
{{- if $rolebinding.subjects }}
subjects:
{{- range $key, $subject := $rolebinding.subjects }}
  - kind: {{ tpl ($subject.kind) $ }}
    name: {{ tpl ($subject.name) $ }}
    namespace: {{ tpl ($subject.namespace) $ }}
{{- if $subject.apiGroup }}
    apiGroup: {{ $subject.apiGroup }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}