{{- if .Values.sealedsecrets }}
{{- $root := . }}
{{- range $name, $sealedsecret := .Values.sealedsecrets }}
{{- if not $sealedsecret.disabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
  {{- range $key, $val :=  $sealedsecret.encryptedData }}
    {{ tpl $key $ }}: {{ tpl $val $ | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
