{{- if .Values.secrets }}
{{- $root := . }}
{{- range $name, $secret := .Values.secrets }}
{{- if not $secret.disabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
type: Opaque
{{- if $secret.data }}
data:
{{ toYaml $secret.data | indent 2 }}
{{- end }}
{{- if $secret.stringData }}
stringData:
{{ toYaml $secret.stringData | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
